#!/bin/sh
set -eu
guix shell openjdk \
     -- java \
     -jar trang-20241231/trang.jar \
     -I dtd \
     -O rnc \
     "$HOME/src/CommonMark/CommonMark-spec/CommonMark.dtd" \
     CommonMark.gen.rnc
